apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app.kubernetes.io/name: demo
spec:
  selector:
    app.kubernetes.io/name: demo
  ports:
    - name: http
      port: 80
      targetPort: 80


